#!/usr/bin/python

import os
import sys

MACHINES = {
    "ofer" : "oferko-ubuntu",
    "ayala" : "ayalash-ThinkPad-W520",
    "yuval" : "tpowner-ThinkPad-W520",
    "eli"   : "tp-elig",
}

if len(sys.argv) == 1:
    print >>sys.stderr, "Missing arguments"
    sys.exit(1)

machineName = MACHINES.get(sys.argv[1]) or sys.argv[1]
print >>sys.stderr, "Connecting to %s..." % machineName
os.system("vncviewer %s" % machineName)
